### ISSUE TITLE
InvalidArgumentError (see above for traceback): indices[104] = 3541 is not in [0, 3541)

### ISSUE THREAD

**Issue by dbl001** [nateraw/Lda2vec-Tensorflow#5]
I'm trying to run 'example_run.py' with Anaconda python 3.6,  tensorflow 1.4.0

InvalidArgumentError (see above for traceback): indices[104] = 3541 is not in [0, 3541)
	 [[Node: nce_loss/negative_sampling/nce_loss/embedding_lookup_1 = Gather[Tindices=DT_INT64, Tparams=DT_FLOAT, _class=["loc:@nce_biases"], validate_indices=true, _device="/job:localhost/replica:0/task:0/device:CPU:0"](nce_biases/read, nce_loss/negative_sampling/nce_loss/concat)]]

**Comment by dbl001** [comment]
```
---------------------------------------------------------------------------
InvalidArgumentError                      Traceback (most recent call last)
~/anaconda/envs/spacy/lib/python3.6/site-packages/tensorflow/python/client/session.py in _do_call(self, fn, *args)
   1322     try:
-> 1323       return fn(*args)
   1324     except errors.OpError as e:

~/anaconda/envs/spacy/lib/python3.6/site-packages/tensorflow/python/client/session.py in _run_fn(session, feed_dict, fetch_list, target_list, options, run_metadata)
   1301                                    feed_dict, fetch_list, target_list,
-> 1302                                    status, run_metadata)
   1303 

~/anaconda/envs/spacy/lib/python3.6/site-packages/tensorflow/python/framework/errors_impl.py in __exit__(self, type_arg, value_arg, traceback_arg)
    472             compat.as_text(c_api.TF_Message(self.status.status)),
--> 473             c_api.TF_GetCode(self.status.status))
    474     # Delete the underlying status object from memory otherwise it stays alive

InvalidArgumentError: indices[104] = 3541 is not in [0, 3541)
	 [[Node: nce_loss/negative_sampling/nce_loss/embedding_lookup_1 = Gather[Tindices=DT_INT64, Tparams=DT_FLOAT, _class=["loc:@nce_biases"], validate_indices=true, _device="/job:localhost/replica:0/task:0/device:CPU:0"](nce_biases/read, nce_loss/negative_sampling/nce_loss/concat)]]

During handling of the above exception, another exception occurred:

InvalidArgumentError                      Traceback (most recent call last)
<ipython-input-1-50d21ae7928f> in <module>()
     35 
     36 # Train the model
---> 37 model.train(pivot_words,target_words,doc_ids, len(pivot_words), 2)
     38 
     39 # Analyze Document Proportions - shape [num_documents, num_topics]

~/Lda2vec-Tensorflow/lda2vec.py in train(self, pivot_words, target_words, doc_ids, data_size, num_epochs)
    176                 doc_batch = doc_ids[i * self.batch_size:i * self.batch_size + self.batch_size]
    177                 summary, _, l, lw2v, llda, step = self.sesh.run([self.merged, self.optimizer, self.loss, self.loss_word2vec, self.loss_lda, self.step],
--> 178                                                                 feed_dict={self.x: x_batch, self.y: y_batch, self.docs: doc_batch})
    179 
    180                 if step > 0 and step % 100 == 0:

~/anaconda/envs/spacy/lib/python3.6/site-packages/tensorflow/python/client/session.py in run(self, fetches, feed_dict, options, run_metadata)
    887     try:
    888       result = self._run(None, fetches, feed_dict, options_ptr,
--> 889                          run_metadata_ptr)
    890       if run_metadata:
    891         proto_data = tf_session.TF_GetBuffer(run_metadata_ptr)

~/anaconda/envs/spacy/lib/python3.6/site-packages/tensorflow/python/client/session.py in _run(self, handle, fetches, feed_dict, options, run_metadata)
   1118     if final_fetches or final_targets or (handle and feed_dict_tensor):
   1119       results = self._do_run(handle, final_targets, final_fetches,
-> 1120                              feed_dict_tensor, options, run_metadata)
   1121     else:
   1122       results = []

~/anaconda/envs/spacy/lib/python3.6/site-packages/tensorflow/python/client/session.py in _do_run(self, handle, target_list, fetch_list, feed_dict, options, run_metadata)
   1315     if handle is None:
   1316       return self._do_call(_run_fn, self._session, feeds, fetches, targets,
-> 1317                            options, run_metadata)
   1318     else:
   1319       return self._do_call(_prun_fn, self._session, handle, feeds, fetches)

~/anaconda/envs/spacy/lib/python3.6/site-packages/tensorflow/python/client/session.py in _do_call(self, fn, *args)
   1334         except KeyError:
   1335           pass
-> 1336       raise type(e)(node_def, op, message)
   1337 
   1338   def _extend_graph(self):

InvalidArgumentError: indices[104] = 3541 is not in [0, 3541)
	 [[Node: nce_loss/negative_sampling/nce_loss/embedding_lookup_1 = Gather[Tindices=DT_INT64, Tparams=DT_FLOAT, _class=["loc:@nce_biases"], validate_indices=true, _device="/job:localhost/replica:0/task:0/device:CPU:0"](nce_biases/read, nce_loss/negative_sampling/nce_loss/concat)]]

Caused by op 'nce_loss/negative_sampling/nce_loss/embedding_lookup_1', defined at:
  File "/Users/davidlaxer/anaconda/envs/spacy/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/Users/davidlaxer/anaconda/envs/spacy/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/Users/davidlaxer/anaconda/envs/spacy/lib/python3.6/site-packages/ipykernel_launcher.py", line 16, in <module>
    app.launch_new_instance()
  File "/Users/davidlaxer/anaconda/envs/spacy/lib/python3.6/site-packages/traitlets/config/application.py", line 658, in launch_instance
    app.start()
  File "/Users/davidlaxer/anaconda/envs/spacy/lib/python3.6/site-packages/ipykernel/kernelapp.py", line 477, in start
    ioloop.IOLoop.instance().start()
  File "/Users/davidlaxer/anaconda/envs/spacy/lib/python3.6/site-packages/zmq/eventloop/ioloop.py", line 177, in start
    super(ZMQIOLoop, self).start()
  File "/Users/davidlaxer/anaconda/envs/spacy/lib/python3.6/site-packages/tornado/ioloop.py", line 888, in start
    handler_func(fd_obj, events)
  File "/Users/davidlaxer/anaconda/envs/spacy/lib/python3.6/site-packages/tornado/stack_context.py", line 277, in null_wrapper
    return fn(*args, **kwargs)
  File "/Users/davidlaxer/anaconda/envs/spacy/lib/python3.6/site-packages/zmq/eventloop/zmqstream.py", line 440, in _handle_events
    self._handle_recv()
  File "/Users/davidlaxer/anaconda/envs/spacy/lib/python3.6/site-packages/zmq/eventloop/zmqstream.py", line 472, in _handle_recv
    self._run_callback(callback, msg)
  File "/Users/davidlaxer/anaconda/envs/spacy/lib/python3.6/site-packages/zmq/eventloop/zmqstream.py", line 414, in _run_callback
    callback(*args, **kwargs)
  File "/Users/davidlaxer/anaconda/envs/spacy/lib/python3.6/site-packages/tornado/stack_context.py", line 277, in null_wrapper
    return fn(*args, **kwargs)
  File "/Users/davidlaxer/anaconda/envs/spacy/lib/python3.6/site-packages/ipykernel/kernelbase.py", line 283, in dispatcher
    return self.dispatch_shell(stream, msg)
  File "/Users/davidlaxer/anaconda/envs/spacy/lib/python3.6/site-packages/ipykernel/kernelbase.py", line 235, in dispatch_shell
    handler(stream, idents, msg)
  File "/Users/davidlaxer/anaconda/envs/spacy/lib/python3.6/site-packages/ipykernel/kernelbase.py", line 399, in execute_request
    user_expressions, allow_stdin)
  File "/Users/davidlaxer/anaconda/envs/spacy/lib/python3.6/site-packages/ipykernel/ipkernel.py", line 196, in do_execute
    res = shell.run_cell(code, store_history=store_history, silent=silent)
  File "/Users/davidlaxer/anaconda/envs/spacy/lib/python3.6/site-packages/ipykernel/zmqshell.py", line 533, in run_cell
    return super(ZMQInteractiveShell, self).run_cell(*args, **kwargs)
  File "/Users/davidlaxer/anaconda/envs/spacy/lib/python3.6/site-packages/IPython/core/interactiveshell.py", line 2698, in run_cell
    interactivity=interactivity, compiler=compiler, result=result)
  File "/Users/davidlaxer/anaconda/envs/spacy/lib/python3.6/site-packages/IPython/core/interactiveshell.py", line 2802, in run_ast_nodes
    if self.run_code(code, result):
  File "/Users/davidlaxer/anaconda/envs/spacy/lib/python3.6/site-packages/IPython/core/interactiveshell.py", line 2862, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-1-50d21ae7928f>", line 34, in <module>
    restore=False)
  File "/Users/davidlaxer/Lda2vec-Tensorflow/lda2vec.py", line 54, in __init__
    handles = self._build_graph()
  File "/Users/davidlaxer/Lda2vec-Tensorflow/lda2vec.py", line 121, in _build_graph
    loss_word2vec = self.w_embed(context, y)
  File "/Users/davidlaxer/Lda2vec-Tensorflow/word_embedding.py", line 52, in __call__
    sampled_values=sampler))
  File "/Users/davidlaxer/anaconda/envs/spacy/lib/python3.6/site-packages/tensorflow/python/ops/nn_impl.py", line 1160, in nce_loss
    name=name)
  File "/Users/davidlaxer/anaconda/envs/spacy/lib/python3.6/site-packages/tensorflow/python/ops/nn_impl.py", line 995, in _compute_sampled_logits
    biases, all_ids, partition_strategy=partition_strategy)
  File "/Users/davidlaxer/anaconda/envs/spacy/lib/python3.6/site-packages/tensorflow/python/ops/embedding_ops.py", line 328, in embedding_lookup
    transform_fn=None)
  File "/Users/davidlaxer/anaconda/envs/spacy/lib/python3.6/site-packages/tensorflow/python/ops/embedding_ops.py", line 150, in _embedding_lookup_and_transform
    result = _clip(_gather(params[0], ids, name=name), ids, max_norm)
  File "/Users/davidlaxer/anaconda/envs/spacy/lib/python3.6/site-packages/tensorflow/python/ops/embedding_ops.py", line 54, in _gather
    return array_ops.gather(params, ids, name=name)
  File "/Users/davidlaxer/anaconda/envs/spacy/lib/python3.6/site-packages/tensorflow/python/ops/array_ops.py", line 2486, in gather
    params, indices, validate_indices=validate_indices, name=name)
  File "/Users/davidlaxer/anaconda/envs/spacy/lib/python3.6/site-packages/tensorflow/python/ops/gen_array_ops.py", line 1834, in gather
    validate_indices=validate_indices, name=name)
  File "/Users/davidlaxer/anaconda/envs/spacy/lib/python3.6/site-packages/tensorflow/python/framework/op_def_library.py", line 787, in _apply_op_helper
    op_def=op_def)
  File "/Users/davidlaxer/anaconda/envs/spacy/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 2956, in create_op
    op_def=op_def)
  File "/Users/davidlaxer/anaconda/envs/spacy/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 1470, in __init__
    self._traceback = self._graph._extract_stack()  # pylint: disable=protected-access

InvalidArgumentError (see above for traceback): indices[104] = 3541 is not in [0, 3541)
	 [[Node: nce_loss/negative_sampling/nce_loss/embedding_lookup_1 = Gather[Tindices=DT_INT64, Tparams=DT_FLOAT, _class=["loc:@nce_biases"], validate_indices=true, _device="/job:localhost/replica:0/task:0/device:CPU:0"](nce_biases/read, nce_loss/negative_sampling/nce_loss/concat)]]
```

**Comment by dbl001** [comment]
On line #82 in "run_20newsgroups.py":

num_docs      = max(doc_ids)+1
